AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  redshiftfb:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 58
      Role: 'arn:aws:iam::773943919453:role/Role_Lambda_Default'
      VpcConfig:
        SecurityGroupIds:
          - sg-0e37ae25ffaf40e4d
        SubnetIds:
          - subnet-04d410df2c0b6403a
      Layers:
        - 'arn:aws:lambda:us-east-1:773943919453:layer:squad28teste:2'
